export const GENERAL_EXPLANATION_CLASS = "bg-emerald-50 text-emerald-950 border-emerald-300";

export const stocks = {
  ABUK: {
    symbol: "ABUK",
    name: "أبو قير للأسمدة",
    sector: "أسمدة وكيماويات",
    price: 61.4,
    avgDailyValueM: 48,
    institutionalOrderM: 8,
    internal: {
      organizedBuying: 82,
      sellingPressureWeakness: 76,
      preMovePressure: 69,
      liquidityQuality: 68,
      overExtensionRisk: 34,
      exhaustionRisk: 29,
      volatilityRisk: 41,
    },
    external: [
      { name: "الدولار", score: 81, relation: "علاقة إيجابية", impact: "داعم", explanation: "عندما يكون الدولار قويًا، قد تستفيد بعض شركات الأسمدة لأنها تبيع أو تسعر جزءًا من منتجاتها بما يرتبط بالدولار. لذلك قوة الدولار هنا تعتبر عاملًا يساعد السهم، لكنها لا تكفي وحدها لاتخاذ قرار شراء." },
      { name: "الغاز والطاقة", score: 62, relation: "تكلفة تشغيل", impact: "مختلط", explanation: "الغاز والطاقة يدخلان في تكلفة إنتاج شركات الأسمدة. ارتفاع التكلفة قد يضغط على الأرباح، لكن إذا كان سعر بيع المنتج قويًا فقد يتم تعويض جزء من هذا الضغط. لذلك أثره هنا ليس إيجابيًا بالكامل ولا سلبيًا بالكامل." },
      { name: "المؤشر الرئيسي", score: 58, relation: "مزاج السوق العام", impact: "داعم محدود", explanation: "تحسن المؤشر الرئيسي يعني أن شهية المستثمرين في السوق أفضل. هذا يساعد تنفيذ الشراء، لكنه ليس سببًا كافيًا وحده لشراء السهم." },
      { name: "الفائدة", score: 37, relation: "ضغط عام على السوق", impact: "ضاغط", explanation: "ارتفاع الفائدة يجعل بعض المستثمرين يفضلون أدوات أقل مخاطرة من الأسهم. لذلك الفائدة المرتفعة قد تضغط على السوق كله، حتى لو كان السهم نفسه جيدًا." },
    ],
    timeline: [
      { session: "-5", stockScore: 54, liquidity: 55, evidence: 61 },
      { session: "-4", stockScore: 58, liquidity: 57, evidence: 64 },
      { session: "-3", stockScore: 63, liquidity: 60, evidence: 70 },
      { session: "-2", stockScore: 68, liquidity: 65, evidence: 78 },
      { session: "اليوم", stockScore: 72, liquidity: 68, evidence: 87 },
    ],
  },
  TMGH: {
    symbol: "TMGH",
    name: "طلعت مصطفى",
    sector: "عقارات",
    price: 72.2,
    avgDailyValueM: 31,
    institutionalOrderM: 12,
    internal: {
      organizedBuying: 43,
      sellingPressureWeakness: 38,
      preMovePressure: 41,
      liquidityQuality: 46,
      overExtensionRisk: 71,
      exhaustionRisk: 66,
      volatilityRisk: 63,
    },
    external: [
      { name: "الفائدة", score: 78, relation: "علاقة سلبية", impact: "ضاغط قوي", explanation: "الشركات العقارية تتأثر كثيرًا بتكلفة التمويل. عندما ترتفع الفائدة، يصبح الاقتراض أغلى على الشركات والعملاء، وقد يقل الطلب أو تتراجع هوامش الربح. لذلك هذا العامل يضعف قرار الشراء." },
      { name: "المؤشر الرئيسي", score: 44, relation: "مزاج السوق العام", impact: "غير داعم", explanation: "ضعف المؤشر الرئيسي يعني أن السوق ليس في حالة إقبال قوية. في هذه الحالة، حتى السهم الجيد قد يجد صعوبة في جذب سيولة جديدة." },
      { name: "الدولار", score: 51, relation: "علاقة غير مباشرة", impact: "مختلط", explanation: "الدولار قد يؤثر على تكلفة مواد البناء أو تقييم الأصول، لكن تأثيره هنا ليس واضحًا بما يكفي ليكون سببًا مباشرًا للشراء أو البيع." },
      { name: "السيولة العامة", score: 39, relation: "قدرة السوق على تنفيذ أوامر كبيرة", impact: "ضاغط", explanation: "عندما تكون السيولة العامة ضعيفة، يصبح دخول أو خروج المستثمر الكبير أصعب، لأنه قد يضطر للشراء بسعر أعلى أو البيع بسعر أقل." },
    ],
    timeline: [
      { session: "-5", stockScore: 66, liquidity: 62, evidence: 69 },
      { session: "-4", stockScore: 61, liquidity: 58, evidence: 62 },
      { session: "-3", stockScore: 56, liquidity: 53, evidence: 55 },
      { session: "-2", stockScore: 50, liquidity: 49, evidence: 48 },
      { session: "اليوم", stockScore: 44, liquidity: 46, evidence: 41 },
    ],
  },
  COMI: {
    symbol: "COMI",
    name: "البنك التجاري الدولي",
    sector: "بنوك",
    price: 88.7,
    avgDailyValueM: 92,
    institutionalOrderM: 10,
    internal: {
      organizedBuying: 61,
      sellingPressureWeakness: 59,
      preMovePressure: 55,
      liquidityQuality: 83,
      overExtensionRisk: 42,
      exhaustionRisk: 37,
      volatilityRisk: 35,
    },
    external: [
      { name: "الفائدة", score: 67, relation: "علاقة إيجابية نسبية", impact: "داعم", explanation: "البنوك قد تستفيد من ارتفاع الفائدة لأنها تحصل على عائد أعلى من الإقراض والاستثمار. لكن الفائدة المرتفعة قد تضغط أيضًا على جودة القروض، لذلك نعتبرها داعمة بشرط عدم تدهور جودة الأصول." },
      { name: "المؤشر الرئيسي", score: 64, relation: "سهم قيادي مرتبط بالسوق", impact: "داعم", explanation: "السهم من الأسهم القيادية. عندما يتحسن السوق الرئيسي، غالبًا يستفيد السهم من دخول سيولة مؤسسية، والعكس صحيح." },
      { name: "الدولار", score: 49, relation: "علاقة غير مباشرة", impact: "محايد", explanation: "الدولار قد يؤثر على الاقتصاد ككل، لكن أثره على هذا السهم في هذه القراءة ليس واضحًا بما يكفي لترجيح قرار الشراء أو البيع." },
      { name: "السيولة العامة", score: 75, relation: "قدرة تنفيذ", impact: "داعم", explanation: "وجود سيولة جيدة في السوق يساعد المؤسسة على الشراء أو البيع دون أن يظهر أثرها بسرعة على السعر." },
    ],
    timeline: [
      { session: "-5", stockScore: 57, liquidity: 78, evidence: 58 },
      { session: "-4", stockScore: 59, liquidity: 80, evidence: 60 },
      { session: "-3", stockScore: 61, liquidity: 82, evidence: 63 },
      { session: "-2", stockScore: 62, liquidity: 83, evidence: 65 },
      { session: "اليوم", stockScore: 63, liquidity: 83, evidence: 67 },
    ],
  },
};

export const glossary = [
  { term: "القرار المؤسسي", meaning: "هو الخلاصة العملية للتقرير: هل الأفضل الشراء، البيع، أم الانتظار؟ كلمة مؤسسي تعني أن القرار لا ينظر للسعر فقط، بل ينظر أيضًا إلى السيولة، حجم التنفيذ، المخاطر، وهل يمكن الدخول بدون رفع السعر ضدنا." },
  { term: "تقييم السهم", meaning: "رقم من 0 إلى 100 يلخص جودة قراءة السهم. الرقم العالي يعني أن المؤشرات الداخلية تميل للإيجابية. الرقم المنخفض يعني أن السهم لا يعطي إشارات كافية أو يعطي إشارات سلبية." },
  { term: "اتفاق الأدلة", meaning: "يقيس هل المؤشرات تؤكد بعضها أم تتعارض. مثال بسيط: إذا كان هناك شراء منظم، وضغط البيع ضعيف، والسيولة تتحسن، فالأدلة متفقة. أما إذا كان السعر يصعد لكن السيولة ضعيفة أو المخاطر عالية، فالأدلة متعارضة." },
  { term: "مستوى المخاطرة", meaning: "يقيس احتمالية أن يكون الدخول غير آمن. المخاطرة ترتفع إذا كان السهم صعد كثيرًا بسرعة، أو الحركة مرهقة، أو التذبذب عالي، أو السيولة ضعيفة." },
  { term: "قابلية بناء مركز", meaning: "تعني هل يستطيع مستثمر كبير شراء كمية مناسبة على عدة جلسات بدون أن يرفع السعر على نفسه. كلما كانت السيولة أعلى وحجم الأمر أقل مقارنة بالتداول، كان بناء المركز أسهل." },
  { term: "خطر كشف الدخول", meaning: "يعني احتمال أن يلاحظ السوق وجود مشتري كبير. لو انكشف الدخول، قد يرتفع السعر بسرعة قبل أن تكمل المؤسسة الشراء، فتدفع سعرًا أعلى من المخطط." },
  { term: "الشراء المنظم", meaning: "يعني أن الطلب على السهم يبدو هادئًا ومتكررًا وليس مجرد قفزة عشوائية. هذا قد يشير إلى دخول تدريجي من مستثمرين جادين، لكنه ليس ضمانًا للربح." },
  { term: "ضعف ضغط البيع", meaning: "يعني أن البائعين لا يضغطون بقوة على السعر. عندما يقل ضغط البيع، يصبح صعود السهم أسهل إذا ظهر طلب جديد." },
  { term: "ضغط قبل الحركة", meaning: "يعني أن السهم قد يكون في مرحلة استعداد قبل حركة أكبر. مثل هدوء السعر مع تحسن تدريجي في الطلب أو السيولة. هذه إشارة تحتاج تأكيدًا ولا تكفي وحدها للشراء." },
];
